spring:
  datasource:
    url: jdbc:mysql://192.168.231.128:3306/demo?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.demo.entity
  mapper-locations: classpath:mapper/*.xml